#!/bin/sh

# Script to see whether argument is positive or negative

if [ $# -eq 0 ]
then
echo "$0 : You must give numerics only"
exit 1
fi
 
if test $1 -gt 0
then
echo "$1 positive number"
else
echo "$1 negative number"
fi
